# Generated by Django 6.0.1 on 2026-01-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='featured/')),
                ('button_text', models.CharField(default='Explore Collection', max_length=50)),
                ('button_link', models.CharField(default='/products/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
