# Generated by Django 6.0.1 on 2026-01-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=60)),
                ('size', models.CharField(blank=True, max_length=60)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['product_id', 'color', 'size'],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
