# Generated by Django 6.0.1 on 2026-01-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_couriersettings_manualnotificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=300)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('mobile', 'Mobile')], default='header', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('open_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['location', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='La Rosa', max_length=120)),
                ('brand_tagline', models.CharField(blank=True, default='Formals', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(blank=True, help_text='Hex color, e.g. #0f172a', max_length=20)),
                ('accent_color', models.CharField(blank=True, help_text='Hex color, e.g. #f59e0b', max_length=20)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=80)),
                ('meta_pixel_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
