# Generated by Codex on 2026-01-24

from django.conf import settings
from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    order_ct, _ = ContentType.objects.get_or_create(app_label="store", model="order")
    payment_ct, _ = ContentType.objects.get_or_create(app_label="store", model="paymenttransaction")
    shipment_ct, _ = ContentType.objects.get_or_create(app_label="store", model="shipment")
    courier_ct, _ = ContentType.objects.get_or_create(app_label="store", model="couriersettings")

    def perms(ct, codenames):
        return list(Permission.objects.filter(content_type=ct, codename__in=codenames))

    finance, _ = Group.objects.get_or_create(name="Finance")
    ops, _ = Group.objects.get_or_create(name="Ops")
    support, _ = Group.objects.get_or_create(name="Support")

    finance.permissions.set(
        perms(payment_ct, ["view_paymenttransaction", "change_paymenttransaction"])
        + perms(order_ct, ["view_order"])
        + perms(shipment_ct, ["view_shipment"])
    )
    ops.permissions.set(
        perms(order_ct, ["view_order", "change_order"])
        + perms(shipment_ct, ["view_shipment", "change_shipment"])
        + perms(courier_ct, ["view_couriersettings", "change_couriersettings"])
    )
    support.permissions.set(
        perms(order_ct, ["view_order"])
        + perms(payment_ct, ["view_paymenttransaction"])
        + perms(shipment_ct, ["view_shipment"])
    )


def remove_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Finance", "Ops", "Support"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_navlink_sitesettings"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
