# Generated by Django 5.0.8 on 2026-02-19 20:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_consentrecord_gdprrequest_historicalconsentrecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("steadfast", "Steadfast"),
                            ("pathao", "Pathao"),
                            ("redx", "RedX"),
                            ("sa_paribahan", "SA Paribahan"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("base_url", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=200)),
                ("api_secret", models.CharField(blank=True, max_length=200)),
                ("client_id", models.CharField(blank=True, max_length=200)),
                ("client_secret", models.CharField(blank=True, max_length=200)),
                ("access_token", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MessagingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sms_provider", models.CharField(blank=True, max_length=80)),
                ("sms_api_key", models.CharField(blank=True, max_length=200)),
                ("sms_sender_id", models.CharField(blank=True, max_length=80)),
                ("whatsapp_provider", models.CharField(blank=True, max_length=80)),
                ("whatsapp_api_key", models.CharField(blank=True, max_length=200)),
                ("whatsapp_sender_id", models.CharField(blank=True, max_length=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("bank", "Bank"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_live", models.BooleanField(default=False)),
                ("base_url", models.URLField(blank=True)),
                ("app_key", models.CharField(blank=True, max_length=200)),
                ("app_secret", models.CharField(blank=True, max_length=200)),
                ("username", models.CharField(blank=True, max_length=120)),
                ("password", models.CharField(blank=True, max_length=120)),
                ("merchant_id", models.CharField(blank=True, max_length=120)),
                ("merchant_private_key", models.TextField(blank=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("event_id", models.CharField(max_length=120, unique=True)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="gdprrequest",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="gdprrequest",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gdprrequest",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="gdprrequest",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="gdprrequest",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalconsentrecord",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalconsentrecord",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalconsentrecord",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalconsentrecord",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalconsentrecord",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalfeaturedbanner",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalfeaturedbanner",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalfeaturedbanner",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalfeaturedbanner",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalfeaturedbanner",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalgdprrequest",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalgdprrequest",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgdprrequest",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalgdprrequest",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalgdprrequest",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalhomebanner",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalhomebanner",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalhomebanner",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalhomebanner",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalhomebanner",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalmanualnotificationlog",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalmanualnotificationlog",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalmanualnotificationlog",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalmanualnotificationlog",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalmanualnotificationlog",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalpaymenttransaction",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalpaymenttransaction",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalpaymenttransaction",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalpaymenttransaction",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalpaymenttransaction",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="historicalshipment",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="homebanner",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="homebanner",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="homebanner",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="homebanner",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="homebanner",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="manualnotificationlog",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="manualnotificationlog",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manualnotificationlog",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="manualnotificationlog",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="manualnotificationlog",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="product",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="shipment",
            name="cod_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="shipment",
            name="cod_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="shipment",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="shipment",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name="HistoricalCourierProviderConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("steadfast", "Steadfast"),
                            ("pathao", "Pathao"),
                            ("redx", "RedX"),
                            ("sa_paribahan", "SA Paribahan"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("base_url", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=200)),
                ("api_secret", models.CharField(blank=True, max_length=200)),
                ("client_id", models.CharField(blank=True, max_length=200)),
                ("client_secret", models.CharField(blank=True, max_length=200)),
                ("access_token", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical courier provider config",
                "verbose_name_plural": "historical courier provider configs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMessagingConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("sms_provider", models.CharField(blank=True, max_length=80)),
                ("sms_api_key", models.CharField(blank=True, max_length=200)),
                ("sms_sender_id", models.CharField(blank=True, max_length=80)),
                ("whatsapp_provider", models.CharField(blank=True, max_length=80)),
                ("whatsapp_api_key", models.CharField(blank=True, max_length=200)),
                ("whatsapp_sender_id", models.CharField(blank=True, max_length=80)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical messaging config",
                "verbose_name_plural": "historical messaging configs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPaymentProviderConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("bank", "Bank"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_live", models.BooleanField(default=False)),
                ("base_url", models.URLField(blank=True)),
                ("app_key", models.CharField(blank=True, max_length=200)),
                ("app_secret", models.CharField(blank=True, max_length=200)),
                ("username", models.CharField(blank=True, max_length=120)),
                ("password", models.CharField(blank=True, max_length=120)),
                ("merchant_id", models.CharField(blank=True, max_length=120)),
                ("merchant_private_key", models.TextField(blank=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical payment provider config",
                "verbose_name_plural": "historical payment provider configs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("event_id", models.CharField(db_index=True, max_length=120)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical payment webhook event",
                "verbose_name_plural": "historical payment webhook events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
