# Generated by Django 5.0.8 on 2026-02-19 20:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_courierproviderconfig_messagingconfig_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReconciliationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("total_pending", models.PositiveIntegerField(default=0)),
                ("reconciled", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("details", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="courierproviderconfig",
            name="refund_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="courierproviderconfig",
            name="token_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="courierproviderconfig",
            name="verify_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="couriersettings",
            name="access_token",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="couriersettings",
            name="refund_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="couriersettings",
            name="token_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="couriersettings",
            name="verify_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcourierproviderconfig",
            name="refund_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcourierproviderconfig",
            name="token_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcourierproviderconfig",
            name="verify_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcouriersettings",
            name="access_token",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="historicalcouriersettings",
            name="refund_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcouriersettings",
            name="token_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcouriersettings",
            name="verify_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalpaymentproviderconfig",
            name="access_token",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="historicalpaymentproviderconfig",
            name="refund_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalpaymentproviderconfig",
            name="signature_format",
            field=models.CharField(
                blank=True, help_text="hex|base64|t=,v1=", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="historicalpaymentproviderconfig",
            name="signature_header",
            field=models.CharField(
                blank=True, help_text="e.g. X-Signature", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="historicalpaymentproviderconfig",
            name="signature_payload",
            field=models.CharField(blank=True, help_text="raw|t+raw", max_length=30),
        ),
        migrations.AddField(
            model_name="historicalpaymentproviderconfig",
            name="token_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalpaymentproviderconfig",
            name="verify_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentproviderconfig",
            name="access_token",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name="paymentproviderconfig",
            name="refund_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentproviderconfig",
            name="signature_format",
            field=models.CharField(
                blank=True, help_text="hex|base64|t=,v1=", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="paymentproviderconfig",
            name="signature_header",
            field=models.CharField(
                blank=True, help_text="e.g. X-Signature", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="paymentproviderconfig",
            name="signature_payload",
            field=models.CharField(blank=True, help_text="raw|t+raw", max_length=30),
        ),
        migrations.AddField(
            model_name="paymentproviderconfig",
            name="token_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentproviderconfig",
            name="verify_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="HistoricalPaymentReconciliationReport",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("run_at", models.DateTimeField(blank=True, editable=False)),
                ("total_pending", models.PositiveIntegerField(default=0)),
                ("reconciled", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("details", models.JSONField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical payment reconciliation report",
                "verbose_name_plural": "historical payment reconciliation reports",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
