# Generated by Django 5.0.8 on 2026-02-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_historicalproduct_meta_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmessagetemplate",
            name="is_html",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="is_html",
            field=models.BooleanField(default=False),
        ),
    ]
